import { useEffect, useId, useRef, useState } from 'react'
import mermaid from 'mermaid'

interface MermaidDiagramProps {
	code: string
	className?: string
}

// mermaid is initialized once with the dark theme so the diagram blends with
// the yz-ui dark glass surfaces. securityLevel 'loose' lets the rendered SVG
// inject styles/fonts without restrictions (the code is generated by us, not
// user-supplied, so this is safe).
let initialized = false
function ensureInit() {
	if (initialized) return
	mermaid.initialize({
		startOnLoad: false,
		theme: 'dark',
		securityLevel: 'loose',
		// useMaxWidth OFF: render the SVG at its natural size and let the
		// container scroll/zoom instead of shrinking the diagram to an
		// unreadable thumbnail inside a narrow modal.
		flowchart: { useMaxWidth: false, htmlLabels: true, curve: 'basis' },
	})
	initialized = true
}

// MermaidDiagram renders Mermaid source code as an SVG diagram inside the
// given container. It re-renders whenever `code` changes.
export default function MermaidDiagram({ code, className }: MermaidDiagramProps) {
	const containerRef = useRef<HTMLDivElement>(null)
	const [svg, setSvg] = useState<string>('')
	const [error, setError] = useState<string | null>(null)
	// mermaid requires a unique id per render; useId gives a stable base we can
	// suffix with a counter to guarantee uniqueness across re-renders.
	const baseId = useId().replace(/[:]/g, '')
	const renderCount = useRef(0)

	useEffect(() => {
		if (!code.trim()) {
			setSvg('')
			setError(null)
			return
		}
		let cancelled = false
		ensureInit()
		renderCount.current += 1
		const id = `mmd-${baseId}-${renderCount.current}`
		// mermaid.render returns a promise in v10+.
		mermaid
			.render(id, code)
			.then(({ svg }) => {
				if (!cancelled) {
					setSvg(svg)
					setError(null)
				}
			})
			.catch((err: unknown) => {
				if (!cancelled) {
					setError(err instanceof Error ? err.message : String(err))
					setSvg('')
				}
			})
		return () => {
			cancelled = true
		}
	}, [code, baseId])

	if (error) {
		return (
			<div className={`mermaid-preview mermaid-error${className ? ` ${className}` : ''}`}>
				<div className="mermaid-error-msg">Could not render the diagram: {error}</div>
				<pre>{code}</pre>
			</div>
		)
	}

	return (
		<div
			ref={containerRef}
			className={`mermaid-preview${className ? ` ${className}` : ''}`}
			// The SVG comes from mermaid's own renderer (trusted, generated by us),
			// so dangerouslySetInnerHTML is safe here.
			dangerouslySetInnerHTML={{ __html: svg }}
		/>
	)
}
