#!/usr/bin/env bash
# skill-registry.sh — Generate the OpenCode skill registry index WITHOUT gentle-ai.
#
# Replaces `gentle-ai skill-registry refresh` / `ywai skill-registry`.
# Scans configured skill directories, reads each SKILL.md frontmatter
# (name, description), and writes a Markdown index that orchestrators
# use to pass exact SKILL.md paths to sub-agents.
#
# Output: <out-dir>/.atl/skill-registry.md  (default: ~/.config/opencode)
#
# Usage:
#   scripts/skill-registry.sh                  # uses default dirs + default out
#   scripts/skill-registry.sh --out /path      # custom output dir
#   scripts/skill-registry.sh --preview        # print to stdout, don't write
#   scripts/skill-registry.sh --cwd /repo      # add a project skills dir
#
# No external deps: bash + awk/sed/grep only. No jq, no yq, no gentle-ai.

set -euo pipefail

OUT_DIR="${HOME}/.config/opencode"
PREVIEW="false"
EXTRA_DIRS=()

# --- Defaults: skill dirs to scan -------------------------------------------
DEFAULT_DIRS=(
  "${HOME}/.config/opencode/skills"
  "${HOME}/.agents/skills"
  "${HOME}/.claude/skills"
)

# Skill dirs to SKIP by name (matches gentle-ai rules: SDD internals, shared, self)
SKIP_NAMES_REGEX='^(sdd-.*|_shared|skill-registry|skill-improver)$'

usage() {
  sed -n '2,18p' "$0"
  exit "${1:-1}"
}

# --- Parse args --------------------------------------------------------------
while [ $# -gt 0 ]; do
  case "$1" in
    --out)    OUT_DIR="$2"; shift 2 ;;
    --preview) PREVIEW="true"; shift ;;
    --cwd)    EXTRA_DIRS+=("$2/skills" "$2/.agents/skills"); shift 2 ;;
    -h|--help) usage 0 ;;
    *) echo "unknown arg: $1" >&2; usage 1 ;;
  esac
done

# --- Helpers -----------------------------------------------------------------

# yaml_field <file> <key>  -> prints first value of `key:` in frontmatter block
yaml_field() {
  local file="$1" key="$2"
  # Only look between the first pair of `---` lines (YAML frontmatter).
  awk -v k="$key" '
    /^---[[:space:]]*$/ { fm++; next }
    fm == 1 {
      # match `key: value` or `key: "value"`
      if (index($0, k ":") == 1) {
        val = substr($0, length(k) + 2)
        sub(/^[[:space:]]*/, "", val)
        # strip surrounding quotes
        sub(/^"/, "", val); sub(/"$/, "", val)
        sub(/^'\''/, "", val); sub(/'\''$/, "", val)
        # trim trailing inline comment + whitespace
        sub(/[[:space:]]*#.*$/, "", val)
        print val
        exit
      }
    }
    fm == 2 { exit }
  ' "$file"
}

# md_escape <string> -> escape pipe chars for Markdown tables
md_escape() { printf '%s' "$1" | sed 's/|/\\|/g; s/`/\\`/g'; }

# --- Collect skills ----------------------------------------------------------
declare -a ROWS=()
SCANNED=""
count=0

scan_dir() {
  local dir="$1" scope="$2"
  [ -d "$dir" ] || return 0
  SCANNED="${SCANNED}- ${dir}\n"

  for skill_md in "$dir"/*/SKILL.md; do
    [ -f "$skill_md" ] || continue
    local sdir skill_name desc
    sdir="$(dirname "$skill_md")"
    skill_name="$(basename "$sdir")"

    # Skip SDD internals, shared, and self-referential registry skills
    if printf '%s' "$skill_name" | grep -Eq "$SKIP_NAMES_REGEX"; then
      continue
    fi

    # Resolve fields: prefer frontmatter, fall back to dir name / placeholder.
    local name desc
    name="$(yaml_field "$skill_md" "name")"
    [ -z "$name" ] && name="$skill_name"
    desc="$(yaml_field "$skill_md" "description")"
    [ -z "$desc" ] && desc="(no description)"

    # Dedupe by skill name: first occurrence (project > user) wins.
    local key=":${name}:"
    if printf '%s\n' "${SEEN:-}" | grep -qF "$key"; then
      continue
    fi
    SEEN="${SEEN:-}${key}"$'\n'

    ROWS+=("| \`${name}\` | $(md_escape "$desc") | ${scope} | \`${skill_md}\` |")
    count=$((count + 1))
  done
}

# Scan project-scoped dirs first (so they win dedupe), then user/global.
for d in "${EXTRA_DIRS[@]:-}"; do scan_dir "$d" "project"; done
for d in "${DEFAULT_DIRS[@]}"; do scan_dir "$d" "user"; done

# --- Build the registry Markdown --------------------------------------------
today="$(date +%Y-%m-%d)"
{
  printf '# Skill Registry\n\n'
  printf '<!-- Auto-generated by scripts/skill-registry.sh (no gentle-ai). Re-run to regenerate. -->\n\n'
  printf 'Last updated: %s\n\n' "$today"
  printf '## Sources scanned\n\n'
  printf '%b' "$SCANNED"
  printf '\n## Contract\n\n'
  printf '**Delegator use only.** This registry is an index, not a summary. '
  printf '`SKILL.md` is the source of truth. Pass exact paths to sub-agents — '
  printf 'do not inline compact rules.\n\n'
  printf '## Skills\n\n'
  printf '| Skill | Trigger / description | Scope | Path |\n'
  printf '| --- | --- | --- | --- |\n'
  if [ "${#ROWS[@]}" -gt 0 ]; then
    printf '%s\n' "${ROWS[@]}"
  else
    printf '| _(none found)_ | | | |\n'
  fi
  printf '\n## Loading protocol\n\n'
  printf '1. Match task context and target files against the Trigger / description column.\n'
  printf '2. Pass only the matching Path values to the sub-agent under `## Skills to load before work`.\n'
  printf '3. Instruct the sub-agent to read those exact `SKILL.md` files before work.\n'
  printf '4. If no matching skill exists, proceed without skill injection and report `skill_resolution: none`.\n'
} > /tmp/skill-registry.$$.md

# --- Emit --------------------------------------------------------------------
if [ "$PREVIEW" = "true" ]; then
  cat /tmp/skill-registry.$$.md
  rm -f /tmp/skill-registry.$$.md
  echo "" >&2
  echo "Preview only — not written. ${count} skill(s) indexed." >&2
  exit 0
fi

mkdir -p "${OUT_DIR}/.atl"
mv /tmp/skill-registry.$$.md "${OUT_DIR}/.atl/skill-registry.md"

echo "Wrote ${OUT_DIR}/.atl/skill-registry.md — ${count} skill(s) indexed." >&2
